### PR TITLE
Update HONO-TSO data

### PR DESCRIPTION
**Pull request by kosamatteo**

### CODE REVIEW

**Comment by RareData** [comment]
The website is giving TLS errors. Please fix.

**Comment by kosamatteo** [comment]
Fixed! Website up and running (@ hono-tso.net!) - Thank you
________________________________
Da: RareData ***@***.***>
Inviato: venerdì 13 gennaio 2023 21:11
A: TowoLabs/ftso-signal-providers ***@***.***>
Cc: kosamatteo ***@***.***>; Author ***@***.***>
Oggetto: Re: [TowoLabs/ftso-signal-providers] Update HONO-TSO data (PR #274)


The website is giving TLS errors. Please fix.

**Comment by RareData** [comment]
Can you please update the logo to not include any whitespace around it?

**Comment by RareData** [comment]
I can see there's still transparency/margin between the icon and the borders. Do you mind removing that? It'll look bad in most wallet software.

**Comment by RareData** [comment]
Fixed in https://github.com/TowoLabs/ftso-signal-providers/commit/2b25addb2b8bdd533effb40f4071ed14b0bca9cc

**Pull request closed without merging**
