### PR TITLE
add Fly2Sonic

### PR DESCRIPTION
**Pull request by fly2sonic**
Hi @RareData 
Could you please check and merge the PR?

### CODE REVIEW

**Comment by RareData** [comment]
Who's the developer, team or entity behind Fly2Sonic?

**Comment by fly2sonic** [comment]
Hi, @RareData 
Thomas Vogt from Norway is the Founder of Fly2Sonic
https://no.linkedin.com/in/thomas-b-vogt-30a5908

**Comment by fly2sonic** [comment]
Hi, @RareData 
Is there any issue on merging my PR?
2 developers of the company are working continuously for running the data provider.
What about having a short call?

**Comment by fly2sonic** [comment]
Hi, @RareData 
Could you please check and merge our PR?

Our provider have been running for more than 2 months.
And I think we have met all requirements written in README.

Please let me know if there is any problem or things to update.
Thanks

**Pull request merged**
