### PR TITLE
FocusTSO - Price provider for Flare FTSO

### PR DESCRIPTION
**Pull request by FocusTSO**
FocusTSO. Data provider built by Focus Global team of developers and Polish Flare community members who run an educational portal in Polish , English and Japanese. The team also provide tools like Airdrop Simulator and recently released Delegation Portal.

### CODE REVIEW

**Comment by FocusTSO** [comment]
FocusTSO Logo 256px

**Review by perlindstroem — CHANGES_REQUESTED** [review]
The PR does not passed `yarn test` as specified in the instructions, the URL should not have a trailing slash.

**Comment by FocusTSO** [comment]
We have just submitted the change - Trailing slash removed

**Comment by FocusTSO** [comment]
Good afternoon,
We have just submited the change .

Regards

Andrzej Mackowiak

W dniu pon., 14.08.2023 o 13:25 Per Lindström ***@***.***>
napisał(a):

**Comment by FocusTSO** [comment]
Requested change done

**Pull request merged**
