### PR TITLE
add edp-ftso on sgb and flare

### PR DESCRIPTION
**Pull request by jonasgitabap**

### CODE REVIEW

**Comment by RareData** [comment]
Please update the icon take up more of the width and height. Leaving a lot of transparent spacing around the icon will look bad in most user interfaces, including Bifrost Wallet.

**Comment by jonasgitabap** [comment]
> Please update the icon take up more of the width and height. Leaving a lot of transparent spacing around the icon will look bad in most user interfaces, including Bifrost Wallet.

updated the logos, should be fine now

**Comment by jonasgitabap** [comment]
@RareData when would you be done with the merge?

**Comment by RareData** [comment]
Please update the image, width and height must be the same (currently 209px by 190px)

**Comment by jonasgitabap** [comment]
Hey @RareData I updated both pngs to 256x256 please recheck. Thanks!

**Pull request merged**
