### PR TITLE
new FTSO provider

### PR DESCRIPTION
**Pull request by g0nx**
Qixote FTSO

### CODE REVIEW

**Comment by RareData** [comment]
Please look over your synchronization to the blockchain and reveal/submit timing.

**Comment by RareData** [comment]
We also recommend you update the image to not include any text. It won't be readable due to the small image size in most clients including Bifrost Wallet.

**Comment by g0nx** [comment]
Hi,

I am working on it, maybe at the end of the week I will get the issues
solved.
Wait for me please.

**Comment by RareData** [comment]
Closed for inactivity

**Pull request closed without merging**
