### PR TITLE
Added SolidiFi Flare address

### PR DESCRIPTION
**Pull request by apfz**

### CODE REVIEW

**Review by perlindstroem — CHANGES_REQUESTED** [review]
Please create a new logo for the new address.

**Comment by apfz** [comment]
@perlindstroem Please see the new commit (4bd8368). I have added a new image for the Flare address and updated the one for Songbird as well.

**Comment by perlindstroem** [comment]
I see the new image, but it does not seem to have been compressed with tinypng @apfz

**Comment by RareData** [comment]
FYI, we've updated our contribution guidelines: https://github.com/TowoLabs/ftso-signal-providers#how-to-add-your-signal-provider and clarified how to run tests locally.

**Comment by apfz** [comment]
@perlindstroem Since the guidelines mentioned tinypng as example I used my own image optimiser (ImageOptim). However, I have re-optimized it now with tinypng and saved an additional 2kb.

**Comment by RareData** [comment]
@apfz either "allow maintainers to update this branch" or solve merge conflicts against master.

**Comment by RareData** [comment]
Added in https://github.com/TowoLabs/ftso-signal-providers/commit/41b1eb24ed8b283ef053ff10ce7aeee301869e21

**Pull request closed without merging**
