### PR TITLE
added info for SGBFTSO

### PR DESCRIPTION
**Pull request by xrpdevs**

### CODE REVIEW

**Comment by RareData** [comment]
Please remove the unused file and optimize your image.

**Comment by xrpdevs** [comment]
The image IS optimized - it is 12.6 KB, half of the maximum size allowed.

I optimized using GIMP, is there a hard requirement to use a third party website to do the optimization?

**Comment by xrpdevs** [comment]
Deleted unused file.

Image is optimized using GIMP, 12.6KB in size so well within the limits.

**Comment by RareData** [comment]
Manually added in:
https://github.com/TowoLabs/ftso-signal-providers/commit/aa97700f74c0f09d0e64b2d8c8dbb064da842eb1
https://github.com/TowoLabs/ftso-signal-providers/commit/d3997a9c9874789b0635f3b07b48715e09c15f17

**Pull request closed without merging**
