### PR TITLE
Register LoveFTSO on Bifrost Wallet

### PR DESCRIPTION
**Pull request by XCBA**

### CODE REVIEW

**Comment by RareData** [comment]
Let's schedule a video call, you can reach out to our company email to get this done.

**Comment by XCBA** [comment]
@RareData I sent messages using "https://flare.network/contact/".
Would you like to tell me how I can schedule a call?
Let me know if my method works.

**Comment by XCBA** [comment]
@RareData Sorry for bothering you again.
I sent a video call request to your company email 7 days ago but did not get any response. 
hello@towolabs.com
Please let me know if this email is correct to contact.

**Comment by RareData** [comment]
We're open for videocalls post-TDE again. Please re-send your email.

**Pull request merged**
