### PR TITLE
Add Nikola-FTSO to songbird providers

### PR DESCRIPTION
**Pull request by NikolaFTSO**

### CODE REVIEW

**Review by perlindstroem — CHANGES_REQUESTED** [review]
* The address does not seem to be actively submitting prices
* The address has not been checksummed

**Comment by RareData** [comment]
FYI, we've updated our contribution guidelines: https://github.com/TowoLabs/ftso-signal-providers#how-to-add-your-signal-provider and clarified how to run tests locally.

**Comment by NikolaFTSO** [comment]
made changes. thank you

**Comment by RareData** [comment]
We can make an exception, so that you can attract enough vote power on the open market too. Will you be able to submit prices once you're listed?

**Comment by NikolaFTSO** [comment]
Yes, please!On Dec 8, 2022, at 14:34, Markus Alvila ***@***.***> wrote:﻿
We can make an exception, so that you can attract enough vote power on the open market too. Will you be able to submit prices once you're listed?

**Pull request merged**
