### PR TITLE
Add Mickey B Fresh

### PR DESCRIPTION
**Pull request by MickeyBFresh**

### CODE REVIEW

**Review by perlindstroem — CHANGES_REQUESTED** [review]
* The image is too big, we allow a max of 35 KB
* The description is too long, max is 250 characters
* http does not redirect to https on the website

**Comment by RareData** [comment]
FYI, we've updated our contribution guidelines: https://github.com/TowoLabs/ftso-signal-providers#how-to-add-your-signal-provider and clarified how to run tests locally.

**Comment by MickeyBFresh** [comment]
> FYI, we've updated our contribution guidelines: https://github.com/TowoLabs/ftso-signal-providers#how-to-add-your-signal-provider and clarified how to run tests locally.

As far as we can tell we updated everything to the correct guidelines. Please let us know, if we still made an error.

**Review by perlindstroem — CHANGES_REQUESTED** [review]
One of the images seems to have a double ".png" and the description is still longer than what is allowed.

**Comment by perlindstroem** [comment]
Closing due to inactivity. Please open a new PR when the issue has been fixed.

**Comment by RareData** [comment]
Included in https://github.com/TowoLabs/ftso-signal-providers/commit/db46a5973c2bea5420d45ce9c7487af724ba6dd0 for next release. We now allow 350 character descriptions and fixed your image filename typo.

**Pull request closed without merging**
