### PR TITLE
Update bifrost-wallet.providerlist.json

### PR DESCRIPTION
**Pull request by praja83**

### CODE REVIEW

**Review by perlindstroem — CHANGES_REQUESTED** [review]
Please add the image you are referring to.

**Comment by praja83** [comment]
0xb6deD9D9CA19af10C67f9A8be8ca75e38E166faA

**Review by perlindstroem — CHANGES_REQUESTED** [review]
Please add the image in the PR.. not in a comment.

**Comment by perlindstroem** [comment]
Duplicate.

**Pull request closed without merging**
