### PR TITLE
Register HXK Oracle on Bifrost Wallet

### PR DESCRIPTION
**Pull request by qlcowboy**

### CODE REVIEW

**Comment by RareData** [comment]
Closed for failure to submit price data in a reliable manner.

**Comment by RareData** [comment]
Example of recent knowingly or unknowingly manipulated/unnatural price submissions: submitted prices

**Comment by qlcowboy** [comment]
Anyway, if it's not a good idea to control submitting prices, then we won't do that.
And also, we will fix our data provider codebase and after then, we will send merge request again.

**Comment by RareData** [comment]
Understood, feel free to submit a new PR once you're done testing and move
to a production-ready FTSO.

**Comment by RareData** [comment]
If you intend to keep sending bogus data to the FTSO system for whatever
reason, use one of the test networks Coston or Coston2.

**Pull request closed without merging**
