### PR TITLE
Add Stakeway for Flare

### PR DESCRIPTION
**Pull request by rushabh101**
Adding the Stakeway operator to FTSO.

The changes in #351 are failing checksum validity tests, I've manually run the tests on my additions after removing the mentioned commit changes, and it is passing tests.

### CODE REVIEW

**Comment by zheli** [comment]
@RareData could you have a look? Thx!

**Comment by zheli** [comment]
@RareData ping

**Comment by zheli** [comment]
@RareData rebased the PR. Could you have a look?

**Comment by RareData** [comment]
> @RareData rebased the PR. Could you have a look?

Could you please center the image, looks good otherwise.

**Pull request merged**
